Annotate DelegateToWidgetMixin's delegate_attribute type
This is needed to avoid mypy's incompatible types assignment:

    urwid/widget.py:1801: error: Incompatible types in assignment (expression has type "str", base class "DelegateToWidgetMixin" defined the type as "None")