Avoid the property trick in DelegateToWidgetMixin class
This confuses mypy which believes that methods definition in base and
child classes are incompatible:

    urwid/graphics.py:100: error: Definition of "sizing" in base class "WidgetDecoration" is incompatible with definition in base class "DelegateToWidgetMixin"
    urwid/graphics.py:100: error: Definition of "selectable" in base class "WidgetDecoration" is incompatible with definition in base class "DelegateToWidgetMixin"

We thus define plain "def" methods for the proxy class.