Ignore mypy error about with_metaclass
Mypy issues errors like:

    urwid/graphics.py:249: error: Unsupported dynamic base class "with_metaclass"

because it does not recognize urwid's "with_metaclass" definition (only
six's one is supported).

We ignore this error message until py2 support gets dropped.