Do not override base class's 'started' property in HtmlGenerator
Instead, we define the '_started' attribute, which is used by 'started'
property in base class.

This fixes the following mypy error:

  urwid/html_fragment.py:47: error: Incompatible types in assignment (expression has type "bool", base class "BaseScreen" defined the type as "property")